apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: calico-cni
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://docs.tigera.io/calico/charts'
    targetRevision: 3.29.1
    chart: tigera-operator
    helm:
      releaseName: calico
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: tigera-operator
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - Replace=true  # Enables replace syncing
    - CreateNamespace=true