apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-controller-chart
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/mohammedd2510/project_testing.git'
    targetRevision: main
    path: nginx-ingress-helm-charts
    helm:
     releaseName: nginx-ingress
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
  timeout: 60  # Timeout in seconds (1 minute)    
