apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: calico-cni
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/mohammedd2510/project_testing.git'
    targetRevision: 3.29.1
    path : calico-chart
    helm:
      releaseName: calico
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: tigera-operator
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
      syncOptions:
      - Replace=true  # Enables replace syncing
      - CreateNamespace=true