apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nti-project-manifests
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/mohammedd2510/NTI-Graduation-Project.git'
    targetRevision: main
    path: project-manifests
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
